### ISSUE TITLE
Linking error

### ISSUE THREAD

**Issue by viktorklochkov** [HeavyIonAnalysis/QnAnalysis#10]
[100%] Linking CXX executable QnAnalysisCorrect
/usr/bin/ld: CMakeFiles/QnAnalysisCorrect.dir/QnCorrectionTask.cpp.o:(.rodata+0x2b8): undefined reference to `Qn::DataContainerHelper::ToErrorComparisonGraph(Qn::DataContainer<Qn::Stats, Qn::Axis<double> > const&)'
/usr/bin/ld: CMakeFiles/QnAnalysisCorrect.dir/QnCorrectionTask.cpp.o:(.rodata+0x2c0): undefined reference to `Qn::DataContainerHelper::ToBootstrapScatterGraph(Qn::DataContainer<Qn::Stats, Qn::Axis<double> > const&)'
/usr/bin/ld: CMakeFiles/QnAnalysisCorrect.dir/QnCorrectionTask.cpp.o:(.rodata+0x2c8): undefined reference to `Qn::DataContainerHelper::ToTMultiGraph(Qn::DataContainer<Qn::Stats, Qn::Axis<double> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Qn::DataContainerHelper::Errors)'

cmake version 3.17.4
gcc (GCC) 10.2.1 20200723 (Red Hat 10.2.1-1)
ROOT Version: 6.22/02

**Comment by eugene274** [comment]
https://github.com/HeavyIonAnalysis/QnAnalysis/blob/b1f35eaf813c50ee1927257c35446a353df0ac92/src/QnAnalysisCorrect/CMakeLists.txt#L16

As you can see there is no QnTools{Base,Correction} in the list of dependencies. However, QnAnalysisBase has both QnToolsBase and QnToolsCorrection. Since they are public they should be passed to QnAnalysisCorrect transparently.

Try to add QnToolsBase to the _target_link_libraries_ of QnAnalysisCorrect.

**Comment by viktorklochkov** [comment]
[ 97%] Linking CXX executable QnAnalysisCorrect
cd /home/vklochkov/Soft/QnAnalysis/cmake-build-debug/src/QnAnalysisCorrect && /home/vklochkov/Soft/clion-2019.2/bin/cmake/linux/bin/cmake -E cmake_link_script CMakeFiles/QnAnalysisCorrect.dir/link.txt --verbose=1
/usr/bin/c++    -std=c++17 -pipe -fsigned-char -pthread -O0 -ggdb -g -DDEBUG -D__DEBUG -Wall   CMakeFiles/QnAnalysisCorrect.dir/QnCorrectionTask.cpp.o CMakeFiles/QnAnalysisCorrect.dir/ATVarManagerTask.cpp.o  -o QnAnalysisCorrect   -L/home/vklochkov/Soft/root/root6/install_17/lib  -Wl,-rpath,/home/vklochkov/Soft/root/root6/install_17/lib:/home/vklochkov/Soft/QnAnalysis/cmake-build-debug/src/QnAnalysisBase:/home/vklochkov/Soft/QnAnalysis/cmake-build-debug/_deps/qntools-build/src/correction:/home/vklochkov/Soft/QnAnalysis/cmake-build-debug/_deps/qntools-build/src/base:/home/vklochkov/Soft/QnAnalysis/cmake-build-debug/_deps/analysistree-build/infra:/home/vklochkov/Soft/QnAnalysis/cmake-build-debug/_deps/analysistree-build/core: ../QnAnalysisConfig/libQnAnalysisConfig.a ../../_deps/attaskskeleton-build/at_task/libat_task_main.a ../QnAnalysisBase/libQnAnalysisBase.so ../../_deps/qntools-build/src/correction/libQnToolsCorrection.so ../../_deps/qntools-build/src/base/libQnToolsBase.so /usr/lib64/libyaml-cpp.so.0.6.3 ../../_deps/attaskskeleton-build/at_task/libat_task.a ../../_deps/analysistree-build/infra/libAnalysisTreeInfra.so ../../_deps/analysistree-build/core/libAnalysisTreeBase.so /home/vklochkov/Soft/root/root6/install_17/lib/libCore.so /home/vklochkov/Soft/root/root6/install_17/lib/libImt.so /home/vklochkov/Soft/root/root6/install_17/lib/libRIO.so /home/vklochkov/Soft/root/root6/install_17/lib/libNet.so /home/vklochkov/Soft/root/root6/install_17/lib/libHist.so /home/vklochkov/Soft/root/root6/install_17/lib/libGraf.so /home/vklochkov/Soft/root/root6/install_17/lib/libGraf3d.so /home/vklochkov/Soft/root/root6/install_17/lib/libGpad.so /home/vklochkov/Soft/root/root6/install_17/lib/libROOTDataFrame.so /home/vklochkov/Soft/root/root6/install_17/lib/libTree.so /home/vklochkov/Soft/root/root6/install_17/lib/libTreePlayer.so /home/vklochkov/Soft/root/root6/install_17/lib/libRint.so /home/vklochkov/Soft/root/root6/install_17/lib/libPostscript.so /home/vklochkov/Soft/root/root6/install_17/lib/libMatrix.so /home/vklochkov/Soft/root/root6/install_17/lib/libPhysics.so /home/vklochkov/Soft/root/root6/install_17/lib/libMathCore.so /home/vklochkov/Soft/root/root6/install_17/lib/libThread.so /home/vklochkov/Soft/root/root6/install_17/lib/libMultiProc.so /home/vklochkov/Soft/root/root6/install_17/lib/libCore.so /usr/lib64/libboost_program_options.so -Wl,-rpath-link,/home/vklochkov/Soft/root/root6/install_17/lib

**Comment by viktorklochkov** [comment]
The problem was on my side. Solved after cleaning the install directory.
