### ISSUE TITLE
Fix initialization of PSI_EVENT_PLANE and correlations containing this type of vectors.

### ISSUE THREAD

**Issue by mam-mih-val** [HeavyIonAnalysis/QnAnalysis#32]
Dear @eugene274,

Please fix the initialization of psi-type vectors. Part of the code corresponding to this functionality is marked as "todo". That is why the correction step doesn't work properly.
Please, check also correlations with psi-vectors. They are empty after the correlation step.

**Comment by eugene274** [comment]
Fixed in linked MR
