### ISSUE TITLE
QA histograms axes in Correction step

### ISSUE THREAD

**Issue by mam-mih-val** [HeavyIonAnalysis/QnAnalysis#42]
Dear @eugene274,

I faced a problem with QA histograms in the Correction step. When setting the axis to the QA histogram given by bin edges, it doesn't work properly. The range of the axis is divided by the number of bins of equal width instead of setting the bins given by the user.
For example, I tried to set this bin edges to the QA histogram:
[0, 0.29375, 0.35625, 0.41875, 0.48125, 0.54375, 0.61875, 0.70625, 0.81875, 1.01875, 2.0]
Instead I got:
10 uniform bins from 0 to 2.

I hope you can sort it out soon,
Thank you in advance!

**Comment by eugene274** [comment]
Bug confirmed for QA: https://github.com/HeavyIonAnalysis/QnTools/issues/49#issue-844471928
